trigger:
  - master
  - devel
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - checkout: self
    - script: cmake -G "Visual Studio 15 2017" -A x64 "-DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)" -S $(Build.SourcesDirectory) -B $(Build.BinariesDirectory)
      displayName: Configure solution with CMake script

    - script: cmake --build $(Build.BinariesDirectory) --config Release
      displayName: Build solution
